version: '3.9'

networks:
  laravel-microservices_app_network:  # Define the shared network
    driver: bridge

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        - APP_PORT=9001
    container_name: auth_service
    ports:
      - "9001:9001"
    volumes:
      - ./auth:/var/www
    networks:
      - laravel-microservices_app_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
      args:
        - APP_PORT=9000
    container_name: products_service
    ports:
      - "9000:9000"
    volumes:
      - ./products:/var/www
    networks:
      - laravel-microservices_app_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx configuration
      - ./auth:/usr/share/nginx/html/auth:ro  # Auth service directory
      - ./products:/usr/share/nginx/html/products:ro  # Products service directory
      - ./services:/usr/share/nginx/html/services:ro  # Services service directory
      - ./certs:/etc/nginx/certs:ro           # SSL certificates (if needed)
    depends_on:
      - auth
      - products
    networks:
      - laravel-microservices_app_network
    restart: unless-stopped
