version: '3.9'

networks:
  laravel-microservices_app_network:
    driver: bridge

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        - APP_PORT=9001
    container_name: auth_service
    ports:
      - "9001:9001"
    volumes:
      - ./auth:/var/www
    networks:
      - laravel-microservices_app_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
      args:
        - APP_PORT=9000
    container_name: products_service
    ports:
      - "9000:9000"
    volumes:
      - ./products:/var/www
    networks:
      - laravel-microservices_app_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY

  notifications:
    build:
      context: ./notifications
      dockerfile: Dockerfile
      args:
        - APP_PORT=9002
    container_name: notifications_service
    ports:
      - "9002:9002"
    volumes:
      - ./notifications:/var/www
    networks:
      - laravel-microservices_app_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
    depends_on:
      - auth
      - products

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./auth:/usr/share/nginx/html/auth:ro
      - ./products:/usr/share/nginx/html/products:ro
      - ./notifications:/usr/share/nginx/html/notifications:ro
      - ./services:/usr/share/nginx/html/services:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - auth
      - products
      - notifications
    networks:
      - laravel-microservices_app_network
    restart: unless-stopped